services:
  - type: web
    name: cn334-yumsalad-back
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn product_service.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: cn334-yumsalad-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: cn334-yumsalad-db
    databaseName: yumsalad
    plan: free 